---
title: "Individual Project Simulation 2"
author: "Ji Yueyi 3035492903"
date: "11/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required packages
```{r}
library(readr)
library(glmnet)
library(knockoff)
library(ggplot2)
library(reshape2)
```

## Load the original data set
```{r}
setwd('/Users/Elaine/Desktop/STAT3799')
data <- read_delim("GSE3330-GPL340.txt", delim = "\t")
sum(is.na(data))
```

## simulation 1: p=20,k=20,nIteration=20
```{r}
nIterations = 20
set.seed(11)
fdp_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),20),]
  data3 <- data2[,-1]
  n=60; p=20; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 20)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:20,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #false discovery proportion
  fdp <- function(selected) sum(beta[selected] == 0) / max(1, length(selected))	
  fdp(lasso_sel)
})
fdp_list_lasso
mean(fdp_list_lasso) ### 0
lasso_fdp_2 <- c(mean(fdp_list_lasso))
```

```{r}
nIterations = 20
set.seed(11)
power_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),20),]
  data3 <- data2[,-1]
  n=60; p=20; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 20)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:20,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #power
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(lasso_sel)
})
power_list_lasso
mean(power_list_lasso)  ###0.8
lasso_power_2 <- c(mean(power_list_lasso))
```

```{r}
Sigma <- diag(1,20)
diag_s = create.solve_asdp(Sigma)

# Compute the fdp over 20 iterations 
nIterations = 20
set.seed(11)
fdp_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),20),]
  data3 <- data2[,-1]
  n=60; p=20; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 20)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:20,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  # Compute and store the fdp
  fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
  fdp(selected)
})

fdp_list_knockoff
# Estimate the FDR
mean(fdp_list_knockoff) ###0
knockoff_fdp_2 <- c(mean(fdp_list_knockoff))
```

```{r}
nIterations = 20
set.seed(11)
power_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),20),]
  data3 <- data2[,-1]
  n=60; p=20; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 20)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:20,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(selected)
})

power_list_knockoff
# Estimate the POWER
mean(power_list_knockoff) ###0.595
knockoff_power_2 <- c(mean(power_list_knockoff))
```

## simulation 2: p=50,k=20,nIteration=20
```{r}
nIterations = 20
set.seed(12)
fdp_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),50),]
  data3 <- data2[,-1]
  n=60; p=50; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 50)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:50,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #false discovery proportion
  fdp <- function(selected) sum(beta[selected] == 0) / max(1, length(selected))	
  fdp(lasso_sel)
})
fdp_list_lasso
mean(fdp_list_lasso) ### 0.4888861
lasso_fdp_2[2] <- c(mean(fdp_list_lasso))
```

```{r}
nIterations = 20
set.seed(12)
power_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),50),]
  data3 <- data2[,-1]
  n=60; p=50; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 50)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:50,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #power
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(lasso_sel)
})
power_list_lasso
mean(power_list_lasso)  ###0.76
lasso_power_2[2] <- c(mean(power_list_lasso))
```

```{r}
Sigma <- diag(1,50)
diag_s = create.solve_asdp(Sigma)

# Compute the fdp over 20 iterations 
nIterations = 20
set.seed(12)
fdp_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),50),]
  data3 <- data2[,-1]
  n=60; p=50; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 50)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:50,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  # Compute and store the fdp
  fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
  fdp(selected)
})

fdp_list_knockoff
# Estimate the FDR
mean(fdp_list_knockoff) ###0.1563037
knockoff_fdp_2[2] <- c(mean(fdp_list_knockoff))
```

```{r}
nIterations = 20
set.seed(12)
power_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),50),]
  data3 <- data2[,-1]
  n=60; p=50; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 50)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:50,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(selected)
})

power_list_knockoff
# Estimate the POWER
mean(power_list_knockoff) ###0.4425
knockoff_power_2[2] <- c(mean(power_list_knockoff))
```

## simulation 3: p=100,k=20,nIteration=20
```{r}
nIterations = 20
set.seed(113)
fdp_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),100),]
  data3 <- data2[,-1]
  n=60; p=100; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 100)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:100,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #false discovery proportion
  fdp <- function(selected) sum(beta[selected] == 0) / max(1, length(selected))	
  fdp(lasso_sel)
})
fdp_list_lasso
mean(fdp_list_lasso) ### 0.604239
lasso_fdp_2[3] <- c(mean(fdp_list_lasso))
```

```{r}
nIterations = 20
set.seed(113)
power_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),100),]
  data3 <- data2[,-1]
  n=60; p=100; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 100)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:100,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #power
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(lasso_sel)
})
power_list_lasso
mean(power_list_lasso)  ###0.75
lasso_power_2[3] <- c(mean(power_list_lasso))
```

```{r}
Sigma <- diag(1,100)
diag_s = create.solve_asdp(Sigma)

# Compute the fdp over 20 iterations 
nIterations = 20
set.seed(113)
fdp_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),100),]
  data3 <- data2[,-1]
  n=60; p=100; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 100)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:100,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  # Compute and store the fdp
  fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
  fdp(selected)
})

fdp_list_knockoff
# Estimate the FDR
mean(fdp_list_knockoff) ###0.310627
knockoff_fdp_2[3] <- c(mean(fdp_list_knockoff))
```

```{r}
nIterations = 20
set.seed(113)
power_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),100),]
  data3 <- data2[,-1]
  n=60; p=100; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 100)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:100,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(selected)
})

power_list_knockoff
# Estimate the POWER
mean(power_list_knockoff) ###0.3925
knockoff_power_2[3] <- c(mean(power_list_knockoff))
```

## simulation 4: p=200,k=20,nIteration=20
```{r}
nIterations = 20
set.seed(114)
fdp_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),200),]
  data3 <- data2[,-1]
  n=60; p=200; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 200)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:200,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #false discovery proportion
  fdp <- function(selected) sum(beta[selected] == 0) / max(1, length(selected))	
  fdp(lasso_sel)
})
fdp_list_lasso
mean(fdp_list_lasso) ### 0.6824151
lasso_fdp_2[4] <- c(mean(fdp_list_lasso))
```

```{r}
nIterations = 20
set.seed(114)
power_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),200),]
  data3 <- data2[,-1]
  n=60; p=200; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 200)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:200,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  #glmnet lasso 
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  #selected important genes
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  #power
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(lasso_sel)
})
power_list_lasso
mean(power_list_lasso)  ###0.665
lasso_power_2[4] <- c(mean(power_list_lasso))
```

```{r}
Sigma <- diag(1,200)
diag_s = create.solve_asdp(Sigma)

# Compute the fdp over 20 iterations 
nIterations = 20
set.seed(114)
fdp_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),200),]
  data3 <- data2[,-1]
  n=60; p=200; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 200)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:200,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  # Compute and store the fdp
  fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
  fdp(selected)
})

fdp_list_knockoff
# Estimate the FDR
mean(fdp_list_knockoff) ###0.3452959
knockoff_fdp_2[4] <- c(mean(fdp_list_knockoff))
```

```{r}
nIterations = 20
set.seed(114)
power_list_knockoff = sapply(1:nIterations, function(it) {
  # Run the knockoff filter manually, using the pre-computed value of diag_s
  data2 <- data[sample(1:(nrow(data)-3),200),]
  data3 <- data2[,-1]
  n=60; p=200; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 200)
  nonzeros <- rnorm(20, 1, 1)
  #50 non-zero factor
  id <- sample(1:200,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(selected)
})

power_list_knockoff
# Estimate the POWER
mean(power_list_knockoff) ###0.29
knockoff_power_2[4] <- c(mean(power_list_knockoff))
```

## simulation 5: p=500,k=20,nIteration=20
```{r}
nIterations = 20
set.seed(15)
fdp_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),500),]
  data3 <- data2[,-1]
  n=60; p=500; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 500)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:500,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  fdp <- function(selected) sum(beta[selected] == 0) / max(1, length(selected))	
  fdp(lasso_sel)
})
fdp_list_lasso
mean(fdp_list_lasso) ### 0.7751933
lasso_fdp_2[5] <- c(mean(fdp_list_lasso))
```

```{r}
nIterations = 20
set.seed(15)
power_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),500),]
  data3 <- data2[,-1]
  n=60; p=500; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 500)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:500,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(lasso_sel)
})
power_list_lasso
mean(power_list_lasso)  ###0.5175
lasso_power_2[5] <- c(mean(power_list_lasso))
```

```{r}
Sigma <- diag(1,500)
diag_s = create.solve_asdp(Sigma)
nIterations = 20
set.seed(15)
fdp_list_knockoff = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),500),]
  data3 <- data2[,-1]
  n=60; p=500; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 500)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:500,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
  fdp(selected)
})

fdp_list_knockoff
mean(fdp_list_knockoff) ###0.5086963
knockoff_fdp_2[5] <- c(mean(fdp_list_knockoff))
```

```{r}
nIterations = 20
set.seed(15)
power_list_knockoff = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),500),]
  data3 <- data2[,-1]
  n=60; p=500; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 500)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:500,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(selected)
})

power_list_knockoff
mean(power_list_knockoff) ###0.225
knockoff_power_2[5] <- c(mean(power_list_knockoff))
```

## simulation 6: p=1000,k=20,nIteration=20
```{r}
nIterations = 20
set.seed(116)
fdp_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),1000),]
  data3 <- data2[,-1]
  n=60; p=1000; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 1000)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:1000,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  fdp <- function(selected) sum(beta[selected] == 0) / max(1, length(selected))	
  fdp(lasso_sel)
})
fdp_list_lasso
mean(fdp_list_lasso) ### 0.8284081
lasso_fdp_2[6] <- c(mean(fdp_list_lasso))
```

```{r}
nIterations = 20
set.seed(116)
power_list_lasso = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),1000),]
  data3 <- data2[,-1]
  n=60; p=1000; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 1000)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:1000,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  cv.model <- cv.glmnet(X,y,alpha = 1,intercept=FALSE)
  model <- coef(cv.model, cv.model$lambda.min)
  selected <- model[model[,1] !=0,1]
  selected_names <- names(selected)
  lasso_sel <- as.numeric(gsub("V","",selected_names[-1]))
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(lasso_sel)
})
power_list_lasso
mean(power_list_lasso)  ###0.355
lasso_power_2[6] <- c(mean(power_list_lasso))
```

```{r}
Sigma <- diag(1,1000)
diag_s = create.solve_asdp(Sigma)
nIterations = 20
set.seed(116)
fdp_list_knockoff = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),1000),]
  data3 <- data2[,-1]
  n=60; p=1000; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 1000)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:1000,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
  fdp(selected)
})
fdp_list_knockoff
mean(fdp_list_knockoff) ###0.5610374
knockoff_fdp_2[6] <- c(mean(fdp_list_knockoff))
```

```{r}
nIterations = 20
set.seed(116)
power_list_knockoff = sapply(1:nIterations, function(it) {
  data2 <- data[sample(1:(nrow(data)-3),1000),]
  data3 <- data2[,-1]
  n=60; p=1000; k=20
  X <- scale(as.matrix(t(data3)))
  beta <- rep(0, 1000)
  nonzeros <- rnorm(20, 1, 1)
  id <- sample(1:1000,20)
  beta[id] <- nonzeros
  error <- rnorm(60,0,1)
  y <- X %*% beta + error
  mu <- colMeans(X)
  X_k = create.gaussian(X, mu, Sigma, diag_s=diag_s)
  W = stat.glmnet_lambdasmax(X, X_k, y)
  t = knockoff.threshold(W, fdr=0.2, offset=1)
  selected = which(W >= t)
  trueDiscoveries <- function(selected) (sum(beta[selected]>0));
  power <- function(selected) (trueDiscoveries(selected)/k);
  power(selected)
})
power_list_knockoff
mean(power_list_knockoff) ###0.1075
knockoff_power_2[6] <- c(mean(power_list_knockoff))
```

```{r}
tab4<- data.frame(
  Simulation_id = c(1:6),
  p = c(20, 50, 100, 200, 500, 1000),
  k = c(20),
  stringsAsFactors = FALSE)
```

```{r}
tab4$lasso_FDR_2 <- lasso_fdp_2
tab4$lasso_power_2 <- lasso_power_2
tab4$knockoff_FDR_2 <- knockoff_fdp_2
tab4$knockoff_power_2 <- knockoff_power_2
tab4
```

## table of fdp comparison
```{r}
tab5 <- data.frame(
  Simulation_id = c(1:6),
  stringsAsFactors = FALSE)
```

```{r}
tab5$lasso_FDR_2 <- lasso_fdp_2
tab5$knockoff_FDR_2 <- knockoff_fdp_2
tab5
tab5_plot <- melt(tab5, id.vars = 'Simulation_id', variable.name = "Selection_method", value.name = "FDR")
ggplot(tab5_plot, aes(Simulation_id , FDR)) + geom_line(aes(colour = Selection_method))
```

## table of power comparison
```{r}
tab6 <- data.frame(
  Simulation_id = c(1:6),
  stringsAsFactors = FALSE)
```

```{r}
tab6$lasso_power_2 <- lasso_power_2
tab6$knockoff_power_2 <- knockoff_power_2
tab6
tab6_plot <- melt(tab6, id.vars = 'Simulation_id', variable.name = "Selection_method", value.name = "Power")
ggplot(tab6_plot, aes(Simulation_id , Power)) + geom_line(aes(colour = Selection_method))
```